name       : gsettings-desktop-schemas
version    : 3.24.1
release    : 38
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/3.24/gsettings-desktop-schemas-3.24.1.tar.xz : 76a3fa309f9de6074d66848987214f0b128124ba7184c958c15ac78a8ac7eea7
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-branding.patch
    %patch -p1 < $pkgfiles/0001-Default-Solus-mouse-settings.patch
    %configure
build      : |
    %make
install    : |
    %make_install
