name       : gsettings-desktop-schemas
version    : 3.28.1
release    : 42
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/3.28/gsettings-desktop-schemas-3.28.1.tar.xz : f88ea6849ffe897c51cfeca5e45c3890010c82c58be2aee18b01349648e5502f
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %apply_patches
    %configure
build      : |
    %make
install    : |
    %make_install
