name       : gsettings-desktop-schemas
version    : 3.38.0
release    : 49
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/3.38/gsettings-desktop-schemas-3.38.0.tar.xz : 5704c8266004b296036671f223c705dc046aa694a1b1abb87c67e7d2747a8c67
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
