name       : gsettings-desktop-schemas
version    : 3.20.0
release    : 34
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gsettings-desktop-schemas/3.20/gsettings-desktop-schemas-3.20.0.tar.xz : 55a41b533c0ab955e0a36a84d73829451c88b027d8d719955d8f695c35c6d9c1
license    :
    - GPL-2.0
summary    : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel: /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-branding.patch
    %patch -p1 < $pkgfiles/0002-Enable-tap-to-click-by-default.patch
    %configure
build      : |
    %make
install    : |
    %make_install
