name       : gsettings-desktop-schemas
version    : '43.0'
release    : 54
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/43/gsettings-desktop-schemas-43.0.tar.xz : 5d5568282ab38b95759d425401f7476e56f8cbf2629885587439f43bd0b84bbe
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
