name       : gsettings-desktop-schemas
version    : '42.0'
release    : 53
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/42/gsettings-desktop-schemas-42.0.tar.xz : 6686335a9ed623f7ae2276fefa50a410d4e71d4231880824714070cb317323d2
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
