name       : gsettings-desktop-schemas
version    : 3.22.0
release    : 36
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gsettings-desktop-schemas/3.22/gsettings-desktop-schemas-3.22.0.tar.xz : 0f06c7ba34c3a99e4d58b10889496133c9aaad6698ea2d8405d481c7f1a7eae1
license    :
    - GPL-2.0
summary    : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-branding.patch
    %patch -p1 < $pkgfiles/0001-Default-Solus-mouse-settings.patch
    %configure
build      : |
    %make
install    : |
    %make_install
