name       : gsettings-desktop-schemas
version    : '41.0'
release    : 51
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/41/gsettings-desktop-schemas-41.0.tar.xz : 77289972e596d044583f0c056306d8f1dbd8adcf912910a50da0a663e65332ed
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
