name       : gsettings-desktop-schemas
version    : 3.28.0
release    : 40
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/3.28/gsettings-desktop-schemas-3.28.0.tar.xz : 4cb4cd7790b77e5542ec75275237613ad22f3a1f2f41903a298cf6cc996a9167
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-branding.patch
    %patch -p1 < $pkgfiles/0001-Default-Solus-mouse-settings.patch
    %configure
build      : |
    %make
install    : |
    %make_install
