name       : gsettings-desktop-schemas
version    : 3.24.0
release    : 37
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gsettings-desktop-schemas/3.24/gsettings-desktop-schemas-3.24.0.tar.xz : f6573a3f661d22ff8a001cc2421d8647717f1c0e697e342d03c6102f29bbbb90
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-branding.patch
    %patch -p1 < $pkgfiles/0001-Default-Solus-mouse-settings.patch
    %configure
build      : |
    %make
install    : |
    %make_install
