name       : gsettings-desktop-schemas
version    : 3.32.0
release    : 44
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/3.32/gsettings-desktop-schemas-3.32.0.tar.xz : 2d59b4b3a548859dfae46314ee4666787a00d5c82db382e97df7aa9d0e310a35
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : The GSettings Desktop Schemas package contains a collection of GSettings
    schemas for settings shared by various components of a GNOME Desktop.
description: |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
