name        : gsettings-desktop-schemas
version     : 3.18.1
release     : 33
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/gsettings-desktop-schemas/3.18/gsettings-desktop-schemas-3.18.1.tar.xz : 258713b2a3dc6b6590971bcfc81f98d78ea9827d60e2f55ffbe40d9cd0f99a1a
license     :
    - GPL-2.0
summary     : The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description : |
    The GSettings Desktop Schemas package contains a collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %patch -p1 < $pkgfiles/0001-Default-branding.patch
    %patch -p1 < $pkgfiles/0002-Enable-tap-to-click-by-default.patch
    %configure
build      : |
    %make
install    : |
    %make_install
